### ISSUE TITLE
GoogleContacts is not a constructor

### ISSUE THREAD

**Issue by karan-jaryal** [Ajnasz/Google-Contacts#7]
var c = new GoogleContacts({
        ^

TypeError: GoogleContacts is not a constructor

getting this error while using the code

**Comment by Ajnasz** [comment]
Well, that's strange, I never published this package, at least, the package is published on npm is not this one. :)

I updated the README, so you can see how to install from github, but I think it will not work very well, because client login is not available on google anymore.
